Repository healthHealther/healthHealtherFE, pull requests merged in 2023-01, with the labels that each got.

#7 Add: 스크롤 탑 버튼 추가
  src/assets/arrow_top.svg
  src/components/ScrollToTop.tsx
Labels: Feature

#9 New/home page
  package-lock.json
  package.json
  src/assets/arrow_back.svg
  src/assets/bell.svg
  src/assets/bell_active.svg
  src/assets/logo.svg
  src/common.tsx
  src/components/NavBar.tsx
  src/components/TopBar.tsx
  src/index.tsx
  src/page/home/HomePage.tsx
Labels: Feature

#10 Add: 메인페이지의 SpaceContentPreview 및 SpaceContentsList 컨포넌트 추가
  src/components/spaceRent/SpaceContentPreview.tsx
  src/components/spaceRent/SpaceContentsList.tsx
  src/index.tsx
  src/page/home/HomePage.tsx
  src/page/spaceRent/SpaceContentPage.tsx
  tailwind.config.js
Labels: Feature

#12 Add: 커뮤니티 미리보기 구현 완료
  src/components/community/BoardContent.tsx
  src/components/community/BoardContentPreview.tsx
  src/components/spaceRent/SpaceContentPreview.tsx
  src/components/spaceRent/SpaceContentsList.tsx
  src/index.tsx
  src/page/community/CommunityContentPage.tsx
  src/page/home/HomePage.tsx
Labels: Feature

#14 Add: 캐러샐 구현 완료
  src/assets/banner_1.png
  src/page/home/BannerCarousel.tsx
  src/page/home/HomePage.tsx
  tailwind.config.js
Labels: Feature

#16 Add: 카테고리 링크 기능 추가
  src/assets/aerobicExerciseIcon.png
  src/assets/gxIcon.png
  src/assets/pilatesIcon.png
  src/page/home/CategoryLink.tsx
  src/page/home/HomePage.tsx
Labels: Feature

#17 Mod: Router 구조 변경 및 그에 따른 컴포넌트 props 삭제
  src/Root.tsx
  src/assets/anaerobicExerciseIcon.png
  src/components/NavBar.tsx
  src/components/NotFound.tsx
  src/components/TopBar.tsx
  src/components/community/BoardContentPreview.tsx
  src/index.tsx
  src/page/home/CategoryLink.tsx
  src/page/home/HomePage.tsx
  src/page/spaceRent/SpaceRentPage.tsx
Labels: documentation

#19 Add: SpaceRentPage에서 인피니티스크롤을 통해 운동 공간 목록 가져 오도록 했고, json-server 적용
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/Root.tsx
  src/components/InfinityScroll.tsx
  src/components/spaceRent/SpaceContentPreview.tsx
  src/components/spaceRent/SpaceContentsList.tsx
  src/db/data.json
  src/index.tsx
  src/mocks/handlers.ts
  src/mocks/worker.ts
  src/page/home/HomePage.tsx
  src/page/spaceRent/SpaceRentPage.tsx
Labels: Feature

#22 Add: 커뮤니티 목록 및 상세 페이지 구현
  package-lock.json
  package.json
  src/Root.tsx
  src/assets/informationIcon.png
  src/common.tsx
  src/components/NavBar.tsx
  src/components/TopBar.tsx
  src/components/community/CommunityContents.tsx
  src/db/data.json
  src/index.tsx
  src/page/community/CommunityContentPage.tsx
  src/page/community/CommunityPage.tsx
  src/page/community/comment/CommentArea.tsx
  src/page/community/comment/CommentItem.tsx
  src/page/community/comment/NewComment.tsx
Labels: Feature

#26 Add: 내정보 페이지 그리기 완료
  src/Root.tsx
  src/assets/logoutIcon.svg
  src/assets/messageIcon.png
  src/assets/randomProfileMan.png
  src/assets/randomProfileWoman.png
  src/assets/rentIcon.png
  src/assets/writeIcon.png
  src/index.tsx
  src/page/myPage/MyPage.tsx
  src/page/myPage/myPageLink/MyPost.tsx
  src/page/myPage/myPageLink/MyRent.tsx
  src/page/myPage/myPageLink/Notification.tsx
Labels: Feature

#27 Add: 페이지 이동시 스크롤 최상단으로 이동
  src/Root.tsx
  src/components/ScrollTopWhenMovePage.tsx
Labels: Feature

#31 Add: 커뮤니티 검색 기능 구현
  src/assets/searchIcon.png
  src/common.tsx
  src/components/ScrollToTop.tsx
  src/components/community/BoardContent.tsx
  src/components/community/CommunityContents.tsx
  src/components/home/BoardContent.tsx
  src/components/home/BoardContentPreview.tsx
  src/db/data.json
  src/page/community/CommunityContents.tsx
  src/page/community/CommunityPage.tsx
  src/page/community/CommunitySearchBar.tsx
  src/page/home/HomePage.tsx
Labels: Feature

#33 Add: 운동 공간 등록하는 폼 작성
  package-lock.json
  package.json
  src/components/spaceRent/GetSpaceContentDetail.ts
  src/components/spaceRent/SpaceContentDetail.tsx
  src/components/spaceRent/SpaceRegister.tsx
  src/index.tsx
  src/interface/space.ts
  src/page/spaceRent/SpaceContentPage.tsx
  src/page/spaceRent/SpaceRegisterPage.tsx
Labels: Feature

#32 Add: 새로운 글 작성하는 버튼 구현
  src/Root.tsx
  src/assets/arrow_top.svg
  src/assets/createButton.png
  src/assets/createButton_1.png
  src/assets/scrollToTop.png
  src/components/CreateNewContentBtn.tsx
  src/components/NavBar.tsx
  src/components/ScrollToTop.tsx
Labels: Feature

#36 Add: SpaceContent 페이지 쿠폰 영역 추가
  src/assets/giftIcon.png
  src/common.tsx
  src/components/spaceRent/Coupon.tsx
  src/components/spaceRent/GetSpaceContentDetail.ts
  src/components/spaceRent/SpaceContentDetail.tsx
  src/components/spaceRent/SpaceContentsList.tsx
  src/components/spaceRent/SpaceRegister.tsx
  src/db/data.json
  src/interface/space.ts
  src/page/spaceRent/SpaceContentPage.tsx
  tailwind.config.js
Labels: Feature

#37 Mod: spaceType 고르는 방식 변경
  package-lock.json
  package.json
  src/components/CreateNewContentBtn.tsx
  src/components/spaceRent/SpaceContentsList.tsx
  src/components/spaceRent/SpaceType.tsx
  src/db/data.json
  src/page/community/CommunityContentPage.tsx
  src/page/community/comment/CommentArea.tsx
  src/page/home/CategoryLink.tsx
  tailwind.config.js
Labels: Feature

#38 Mod: 운동공간 상세 페이지 CSS 수정된 사항 편의상항 제외하고 적용
  package-lock.json
  package.json
  public/index.html
  src/common.tsx
  src/components/spaceRent/GetSpaceReview.ts
  src/components/spaceRent/NewReview.tsx
  src/components/spaceRent/SpaceContentDetail.tsx
  src/components/spaceRent/SpaceConvenience.tsx
  src/components/spaceRent/SpaceCoupon.tsx
  src/components/spaceRent/SpaceDetailInfo.tsx
  src/components/spaceRent/SpaceMap.tsx
  src/components/spaceRent/SpaceRentBtn.tsx
  src/components/spaceRent/SpaceReview.tsx
  src/components/spaceRent/SpaceRule.tsx
  src/db/data.json
  src/interface/space.ts
  tailwind.config.js
  tsconfig.json
Labels: Feature

#39 Mod: SpaceRegister 페이지에서 주소 입력할 때 카카오 주소 api 를 통해 입력하게 수정
  package-lock.json
  package.json
  src/assets/deleteIcon.png
  src/assets/uploadIcon.png
  src/components/CreateNewContentBtn.tsx
  src/components/spaceRent/NewReview.tsx
  src/components/spaceRent/SpaceRegister.tsx
  src/components/spaceRent/SpaceSelectBox.tsx
  src/db/data.json
  src/index.css
  src/interface/space.ts
  src/page/community/CommunityContentPage.tsx
  tailwind.config.js
Labels: Feature

#40 Add: 홈짐 등록 이미지 미리보기 모달 추가
  src/components/spaceRent/SpaceRegister.tsx
  src/components/spaceRent/register/ImagePreview.tsx
Labels: Feature

#42 [Feature] 게시글 등록및 모달 팝업
  package-lock.json
  package.json
  src/assets/cancelLikeIcon.png
  src/assets/doLikeIcon.png
  src/assets/likeIcon.png
  src/components/ConfirmPopUp.tsx
  src/components/CreateNewContentBtn.tsx
  src/components/ScrollToTop.tsx
  src/components/home/BoardContent.tsx
  src/components/spaceRent/SpaceContentsList.tsx
  src/components/spaceRent/SpaceType.tsx
  src/db/data.json
  src/index.css
  src/index.tsx
  src/page/community/CommunityRegisterPage.tsx
  src/page/community/LikeArea.tsx
  src/page/community/comment/NewComment.tsx
Labels: Feature

#45 fix: 홈짐 등록 페이지 submit 버튼 오류 수정
  package-lock.json
  package.json
  src/components/spaceRent/SpaceSelectBox.tsx
  src/components/spaceRent/register/ImageUpload.tsx
  src/components/spaceRent/register/InputAddress.tsx
  src/components/spaceRent/register/InputPrice.tsx
  src/components/spaceRent/register/InputTitle.tsx
  src/components/spaceRent/register/RegisterBtn.tsx
  src/components/spaceRent/register/RegisterSelectBox.tsx
  src/components/spaceRent/register/SelectTime.tsx
  src/components/spaceRent/register/SpaceRegister.tsx
  src/components/spaceRent/register/TextAreaContent.tsx
  src/components/spaceRent/register/style.ts
  src/components/spaceRent/reservation/ReservationCoupon.tsx
  src/components/spaceRent/reservation/ReservationTimeSelect.tsx
  src/db/data.json
  src/page/spaceRent/SpaceReservation.tsx
Labels: fix

#46 Add: 백엔드 연동해서 카카오 로그인 적용
  package-lock.json
  package.json
  src/components/login/cookie.ts
  src/components/login/kakaoLogin.ts
  src/index.tsx
  src/page/login/InputMemberInfo.tsx
  src/page/login/LoginRedirect.tsx
  src/page/myPage/MyPage.tsx
  src/setupProxt.js
Labels: Feature

#47 [Feature] Google 로그인 구현
  src/components/OAuth.tsx
  src/components/login/OAuthLogin.ts
  src/components/login/googleLogin.ts
  src/components/spaceRent/SpaceType.tsx
  src/index.css
  src/index.tsx
  src/page/login/InputMemberInfo.tsx
  src/page/login/LoginPage.tsx
  src/page/login/LoginRedirect.tsx
Labels: Feature

#48 [Mod] 커뮤니티 api 연결
  package-lock.json
  package.json
  src/components/Spinner.tsx
  src/components/TokenRefresh.tsx
  src/components/home/BoardContent.tsx
  src/components/home/BoardContentPreview.tsx
  src/components/login/googleLogin.ts
  src/components/spaceRent/GetSpaceContentDetail.ts
  src/components/spaceRent/SpaceContentsList.tsx
  src/index.tsx
  src/page/community/CommunityContentPage.tsx
  src/page/community/CommunityContents.tsx
  src/page/community/CommunityPage.tsx
  src/page/community/CommunityRegisterPage.tsx
  src/page/community/CommunitySearchBar.tsx
  src/page/community/LikeArea.tsx
  src/page/community/comment/CommentArea.tsx
  src/page/community/comment/CommentItem.tsx
  src/page/community/comment/NewComment.tsx
Labels: Mod

#51 Add: 홈짐 목록 페이지 검색 기능 추가
  src/assets/search.png
  src/common.tsx
  src/components/spaceRent/SearchBar.tsx
  src/components/spaceRent/SpaceContentsList.tsx
  src/page/spaceRent/SpaceRentPage.tsx
Labels: Feature

#52 Mod: 홈짐 상세 페이지 백엔드 api로 데이터 불러오게 변경
  src/common.tsx
  src/components/spaceRent/GetSpaceContentDetail.ts
  src/components/spaceRent/SpaceContentsList.tsx
  src/components/spaceRent/content/SpaceContentDetail.tsx
  src/components/spaceRent/content/SpaceDetailInfo.tsx
  src/components/spaceRent/reservation/ReservationTimeSelect.tsx
  src/page/spaceRent/SpaceContentPage.tsx
  src/page/spaceRent/SpaceReservation.tsx
Labels: Mod
